[workspace]
members = [
    "hello_world",
    "guessing_game",
    "variables",
    "ownership",
    "structs",
    "rectangles",
    "enums",
    "restaurant",
    "common_collections",
    "common_collections_exercices",
    "error-handling",
    "generics",
    "adder"
]
